using Newtonsoft.Json;
using System;

namespace GSMA.MobileConnect.Authentication
{
    /// <summary>
    /// A class that holds a valid response from <see cref="IAuthenticationService.RequestTokenAsync(string, string, string, string, string, string)"/>
    /// </summary>
    /// <seealso cref="RequestTokenResponse"/>
    public class RequestTokenResponseData
    {
        /// <summary>
        /// The time the response was received
        /// </summary>
        [JsonProperty("time_received")]
        public DateTime TimeReceived { get; private set; }

        /// <summary>
        /// The OAuth 2.0 access token generated by the authorization server
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; private set; }

        /// <summary>
        /// The type of the access token generated (should be "Bearer")
        /// </summary>
        [JsonProperty("token_type")]
        public string TokenType { get; private set; }

        /// <summary>
        /// Additional token used in OIDC to provide the identity token claim
        /// </summary>
        [JsonProperty("id_token")]
        public string IdToken { get; private set; }

        /// <summary>
        /// The optional refresh token generated by the authorization server
        /// </summary>
        [JsonProperty("refresh_token")]
        public string RefreshToken { get; private set; }

        /// <summary>
        /// The time the response will expire, this is calculated using the time received and expires in values.
        /// </summary>
        [JsonIgnore]
        public DateTime? Expiry { get; private set; }

        private int? _expiresIn;
        /// <summary>
        /// The number of seconds from time recieved to expiry
        /// </summary>
        [JsonProperty("expires_in")]
        public int? ExpiresIn
        {
            get { return _expiresIn; }
            set
            {
                _expiresIn = value;
                Expiry = CalculateExpiry(TimeReceived, value);
            }
        }

        /// <summary>
        /// correlation_id
        /// </summary>
        [JsonProperty("correlation_id")]
        public string CorrelationId { get; private set; }

        /// <inheritdoc />
        public RequestTokenResponseData()
        {
            this.TimeReceived = DateTime.UtcNow;
        }

        /// <summary>
        /// Calculate the expires value
        /// </summary>
        private DateTime? CalculateExpiry(DateTime timeReceived, int? expiresIn)
        {
            if (!expiresIn.HasValue)
            {
                return null;
            }

            return timeReceived.AddSeconds(expiresIn.Value);
        }
    }
}
